# Generated by Django 5.0.6 on 2025-08-14 04:20

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flash_promo', '0001_postgis_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('brand', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='flash_promo_geom_a4df6b_gist')],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash_promo.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash_promo.store')),
            ],
            options={
                'unique_together': {('store', 'product')},
            },
        ),
        migrations.CreateModel(
            name='FlashPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('ACTIVE', 'Activa'), ('FINISHED', 'Finalizado')], default='SCHEDULED', max_length=12)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash_promo.storeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateField(default=django.utils.timezone.localdate)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash_promo.flashpromo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['promo', 'sent_at'], name='flash_promo_promo_i_7562a1_idx')],
                'unique_together': {('user', 'promo', 'sent_date')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_new_user', models.BooleanField(default=False)),
                ('is_frequent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='flash_promo_geom_01e9ca_gist')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('HOLD', 'Retenido'), ('CONFIRMED', 'Confirmado'), ('CANCELED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='HOLD', max_length=12)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flash_promo.flashpromo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flash_promo.storeproduct')),
            ],
            options={
                'indexes': [models.Index(fields=['store_product', 'status'], name='flash_promo_store_p_c2dd48_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='flashpromo',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='flash_promo_status_788319_idx'),
        ),
        migrations.AddIndex(
            model_name='flashpromo',
            index=models.Index(fields=['store_product', 'starts_at'], name='flash_promo_store_p_3b8666_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashpromo',
            constraint=models.CheckConstraint(check=models.Q(('starts_at__lt', models.F('ends_at'))), name='promo_valid_window'),
        ),
    ]
